version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: crm

  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - .env

volumes:
  mongo-data:
